# frozen_string_literal: true

source "http://rubygems.org"

 gem "rspec"
 gem "cucumber"
 gem "selenium-webdriver"
 gem "capybara"
 gem "site_prism" 
 gem "faker"
 gem 'poltergeist'
 gem "json", "~> 1.8.1"
 gem "capybara-angular"